package com.matcha.myapplication;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;

import com.matcha.myapplication.dao.Action;
import com.matcha.myapplication.dao.ActionDAO;
import com.matcha.myapplication.dao.Game;
import com.matcha.myapplication.dao.GameDAO;
import com.matcha.myapplication.dao.Player;
import com.matcha.myapplication.dao.PlayerDAO;
import com.matcha.myapplication.dao.Team;
import com.matcha.myapplication.dao.TeamDAO;

import java.util.ArrayList;


public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    public void click1(View v)
    {
        Intent it=new Intent(MainActivity.this,TabActivity.class);
        startActivity(it);
    }
    public void click2(View v)
    {
        ActionDAO dao=new ActionDAO(MainActivity.this);
        Action action=new Action("1",1,"7",9);
        dao.insertAction(action);
        action=new Action("1",2,"7",7);
        dao.insertAction(action);
        action=new Action("1",3,"7",2);
        dao.insertAction(action);
        action=new Action("1",4,"8",7);
        dao.insertAction(action);
        action=new Action("1",1,"14",4);
        dao.insertAction(action);
        action=new Action("1",2,"14",13);
        dao.insertAction(action);
        action=new Action("1",3,"8",13);
        dao.insertAction(action);
        action=new Action("1",4,"7",8);
        dao.insertAction(action);
        action=new Action("1",1,"14",8);
        dao.insertAction(action);
        action=new Action("1",2,"7",8);
        dao.insertAction(action);
        action=new Action("1",3,"7",2);
        dao.insertAction(action);
        action=new Action("1",4,"8",2);
        dao.insertAction(action);
        action=new Action("1",1,"8",7);
        dao.insertAction(action);
        action=new Action("1",4,"7",2);
        dao.insertAction(action);
        action=new Action("1",3,"7",8);
        dao.insertAction(action);
        action=new Action("1",2,"7",9);
        dao.insertAction(action);
        action=new Action("1",1,"8",13);
        dao.insertAction(action);
        action=new Action("1",1,"7",7);
        dao.insertAction(action);
        action=new Action("1",2,"8",12);
        dao.insertAction(action);
        action=new Action("1",3,"14",4);
        dao.insertAction(action);
        action=new Action("1",4,"7",12);
        dao.insertAction(action);
        action=new Action("1",1,"14",12);
        dao.insertAction(action);
        action=new Action("1",2,"7",13);
        dao.insertAction(action);
        action=new Action("1",3,"6",11);
        dao.insertAction(action);
        action=new Action("1",4,"8",2);
        dao.insertAction(action);
        action=new Action("1",1,"7",2);
        dao.insertAction(action);
        action=new Action("1",2,"7",9);
        dao.insertAction(action);
        action=new Action("1",3,"7",7);
        dao.insertAction(action);
        action=new Action("1",4,"8",10);
        dao.insertAction(action);
        action=new Action("1",1,"8",2);
        dao.insertAction(action);
        action=new Action("1",2,"8",9);
        dao.insertAction(action);
        action=new Action("1",3,"7",13);
        dao.insertAction(action);
        action=new Action("1",4,"14",3);
        dao.insertAction(action);
        action=new Action("1",1,"8",12);
        dao.insertAction(action);
        action=new Action("1",2,"7",2);
        dao.insertAction(action);
        action=new Action("1",3,"7",2);
        dao.insertAction(action);
        action=new Action("1",4,"8",2);
        dao.insertAction(action);
        action=new Action("1",1,"14",8);
        dao.insertAction(action);
        action=new Action("1",2,"7",12);
        dao.insertAction(action);
        action=new Action("1",3,"8",9);
        dao.insertAction(action);
        action=new Action("1",4,"8",2);
        dao.insertAction(action);
        action=new Action("1",1,"7",1);
        dao.insertAction(action);
        action=new Action("1",2,"8",1);
        dao.insertAction(action);
        action=new Action("1",3,"8",13);
        dao.insertAction(action);
        action=new Action("1",4,"7",7);
        dao.insertAction(action);
        action=new Action("1",1,"8",4);
        dao.insertAction(action);
        action=new Action("1",2,"8",12);
        dao.insertAction(action);
        action=new Action("1",3,"8",9);
        dao.insertAction(action);
        action=new Action("1",4,"7",9);
        dao.insertAction(action);
        action=new Action("1",1,"7",13);
        dao.insertAction(action);
        action=new Action("1",2,"14",4);
        dao.insertAction(action);
        action=new Action("1",3,"7",7);
        dao.insertAction(action);
        action=new Action("1",4,"7",8);
        dao.insertAction(action);
        action=new Action("1",1,"8",13);
        dao.insertAction(action);
        action=new Action("1",2,"7",13);
        dao.insertAction(action);
        action=new Action("1",3,"8",2);
        dao.insertAction(action);
        action=new Action("1",4,"7",8);
        dao.insertAction(action);
        action=new Action("1",1,"8",2);
        dao.insertAction(action);
        action=new Action("1",2,"14",13);
        dao.insertAction(action);
        action=new Action("1",3,"3",12);
        dao.insertAction(action);
        action=new Action("1",4,"7",2);
        dao.insertAction(action);
        action=new Action("1",1,"8",10);
        dao.insertAction(action);
        action=new Action("1",2,"14",4);
        dao.insertAction(action);
        action=new Action("1",3,"16",10);
        dao.insertAction(action);
        action=new Action("1",4,"20",1);
        dao.insertAction(action);
        action=new Action("1",1,"20",2);
        dao.insertAction(action);
        action=new Action("1",2,"20",2);
        dao.insertAction(action);
        action=new Action("1",3,"20",4);
        dao.insertAction(action);
        action=new Action("1",4,"20",4);
        dao.insertAction(action);
        action=new Action("1",2,"20",10);
        dao.insertAction(action);
        action=new Action("1",3,"20",10);
        dao.insertAction(action);
        action=new Action("1",4,"20",9);
        dao.insertAction(action);
        action=new Action("1",1,"20",9);
        dao.insertAction(action);
        action=new Action("1",2,"20",7);
        dao.insertAction(action);
        action=new Action("1",3,"24",1);
        dao.insertAction(action);
        action=new Action("1",4,"24",1);
        dao.insertAction(action);
        action=new Action("1",1,"24",2);
        dao.insertAction(action);
        action=new Action("1",2,"24",2);
        dao.insertAction(action);
        action=new Action("1",3,"24",2);
        dao.insertAction(action);
        action=new Action("1",4,"24",2);
        dao.insertAction(action);
        action=new Action("1",1,"24",2);
        dao.insertAction(action);
        action=new Action("1",2,"24",2);
        dao.insertAction(action);
        action=new Action("1",3,"24",2);
        dao.insertAction(action);
        action=new Action("1",4,"24",2);
        dao.insertAction(action);
        action=new Action("1",1,"24",3);
        dao.insertAction(action);
        action=new Action("1",2,"24",3);
        dao.insertAction(action);
        action=new Action("1",3,"24",4);
        dao.insertAction(action);
        action=new Action("1",4,"24",4);
        dao.insertAction(action);
        action=new Action("1",1,"24",4);
        dao.insertAction(action);
        action=new Action("1",2,"24",5);
        dao.insertAction(action);
        action=new Action("1",3,"24",5);
        dao.insertAction(action);
        action=new Action("1",4,"24",6);
        dao.insertAction(action);
        action=new Action("1",1,"24",6);
        dao.insertAction(action);
        action=new Action("1",2,"24",10);
        dao.insertAction(action);
        action=new Action("1",3,"24",10);
        dao.insertAction(action);
        action=new Action("1",4,"24",9);
        dao.insertAction(action);
        action=new Action("1",1,"24",9);
        dao.insertAction(action);
        action=new Action("1",2,"24",9);
        dao.insertAction(action);
        action=new Action("1",1,"24",13);
        dao.insertAction(action);
        action=new Action("1",4,"24",7);
        dao.insertAction(action);
        action=new Action("1",1,"24",7);
        dao.insertAction(action);
        action=new Action("1",2,"24",8);
        dao.insertAction(action);
        action=new Action("1",3,"24",12);
        dao.insertAction(action);
        action=new Action("1",4,"24",12);
        dao.insertAction(action);
        action=new Action("1",1,"24",12);
        dao.insertAction(action);
        action=new Action("1",2,"24",12);
        dao.insertAction(action);
        action=new Action("1",3,"24",12);
        dao.insertAction(action);
        action=new Action("1",4,"24",12);
        dao.insertAction(action);
        action=new Action("1",4,"24",12);
        dao.insertAction(action);
        action=new Action("1",3,"25",1);
        dao.insertAction(action);
        action=new Action("1",2,"25",1);
        dao.insertAction(action);
        action=new Action("1",1,"25",1);
        dao.insertAction(action);
        action=new Action("1",1,"25",2);
        dao.insertAction(action);
        action=new Action("1",2,"25",2);
        dao.insertAction(action);
        action=new Action("1",3,"25",4);
        dao.insertAction(action);
        action=new Action("1",4,"25",5);
        dao.insertAction(action);
        action=new Action("1",1,"25",5);
        dao.insertAction(action);
        action=new Action("1",2,"25",5);
        dao.insertAction(action);
        action=new Action("1",3,"25",6);
        dao.insertAction(action);
        action=new Action("1",4,"25",6);
        dao.insertAction(action);
        action=new Action("1",1,"25",9);
        dao.insertAction(action);
        action=new Action("1",2,"25",8);
        dao.insertAction(action);
        action=new Action("1",3,"25",8);
        dao.insertAction(action);
        action=new Action("1",4,"25",12);
        dao.insertAction(action);
        action=new Action("1",1,"25",12);
        dao.insertAction(action);
        action=new Action("1",2,"25",12);
        dao.insertAction(action);
        action=new Action("1",3,"25",12);
        dao.insertAction(action);
        action=new Action("1",4,"25",12);
        dao.insertAction(action);
        action=new Action("1",4,"25",12);
        dao.insertAction(action);
        action=new Action("1",2,"25",13);
        dao.insertAction(action);
        action=new Action("1",1,"25",13);
        dao.insertAction(action);
        action=new Action("1",3,"25",13);
        dao.insertAction(action);
        action=new Action("1",4,"25",13);
        dao.insertAction(action);
        action=new Action("1",1,"17",12);
        dao.insertAction(action);

        ArrayList<Player> list=new ArrayList<>();
        list.add(new Player("1","3","Name1"));
        list.add(new Player("1","6","Name2"));
        list.add(new Player("1","7","Name3"));
        list.add(new Player("1","8","Name4"));
        list.add(new Player("1","11","Name5"));
        list.add(new Player("1","14","Name6"));
        list.add(new Player("1","16","Name7"));
        list.add(new Player("1","20","Name8"));
        list.add(new Player("1","24","Name9"));
        list.add(new Player("1","25","Name10"));
        list.add(new Player("1","40","Name11"));
        list.add(new Player("1","17","Name12"));
        PlayerDAO playerDAO=new PlayerDAO(MainActivity.this);
        playerDAO.insertPlayers(list);

        GameDAO gameDAO=new GameDAO(MainActivity.this);
        ArrayList<Game> games=new ArrayList<>();
        Game g=new Game("2",1,"3",5,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        g=new Game("2",2,"3",4,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        g=new Game("2",3,"5",8,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        g=new Game("2",4,"9",4,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        g=new Game("3",1,"23",5,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        g=new Game("3",2,"65",5,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        g=new Game("3",3,"3",5,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        g=new Game("3",4,"45",5,1,1,2,2,3,3,1,1,1,1,1,1,5);
        games.add(g);
        gameDAO.insertGames(games);

        TeamDAO teamDAO=new TeamDAO(this);
        teamDAO.insertTeam(new Team("Team1","Team2",100,87));
        teamDAO.insertTeam(new Team("隊伍1","隊伍2",90,90));
        teamDAO.insertTeam(new Team("隊伍3","隊伍4",80,75));
        teamDAO.insertTeam(new Team("隊伍5","隊伍6",89,88));

    }
}
